# Generated by Django 3.2.17 on 2023-02-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20230223_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUnpublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Unpublished Video',
                'verbose_name_plural': 'Unpublished Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
