# Generated by Django 3.2.5 on 2023-02-24 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_publish_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoActiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Active Video',
                'verbose_name_plural': 'Active Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
        migrations.CreateModel(
            name='VideoInactiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Video',
                'verbose_name_plural': 'Inactive Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
