# Generated by Django 3.2.17 on 2023-03-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_alter_playlist_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SEA', 'Season'), ('PLY', 'Playlist')], default='PLY', max_length=3),
        ),
    ]
